version: '3.8'
services:
  backend:
    container_name: unipoint-backend
    build: ./backend
    restart: always
    environment:
      DB_HOST: unipoint-db.clg8clb9ersw.us-east-2.rds.amazonaws.com
      DB_PORT: 5432
      DB_USERNAME: unipoint_user
      DB_PASSWORD: unipoint_pass
      DB_DATABASE: unipoint_db
    ports:
      - '4000:4000'

  frontend:
    container_name: unipoint-frontend
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - '80:80'

volumes:
  db_data: 